### ISSUE TITLE
bgm and voice files won't download

### ISSUE THREAD

**Issue by Kavolc** [MightyZanark/PriconneUtils#5]
I keep getting:
File [bgm_MS06.awb] already exists
File [bgm_MS07.acb] already exists
File [bgm_MS07.awb] already exists
File [bgm_MS08.acb] already exists
File [bgm_MS08.awb] already exists
File [bgm_S01.acb] already exists
File [bgm_S01.awb] already exists

**Comment by MightyZanark** [comment]
Oh right I was going to fix that alongside the manifest update but seems like I just forgot about that. I'll fix it this weekend

**Comment by MightyZanark** [comment]
i completely forgot about this but its fixed now thanks to @XiaoLu-Ling making a pull request (https://github.com/MightyZanark/PriconneUtils/pull/6)
